name: ruta9_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  video_player: ^2.7.0
  url_launcher: ^6.2.6
  font_awesome_flutter: ^10.7.0
  csv: ^5.1.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/welcome.mp4
    - assets/images/logos/R9.png
    - assets/data/ # Add this line to include the new data directory
